"""added subsription table

Revision ID: 16138ef7d66e
Revises: 82cdf46e9a88
Create Date: 2019-07-07 23:24:21.178707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16138ef7d66e'
down_revision = '82cdf46e9a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
